name: Publish Docker image
permissions:
  contents: read
  packages: write
on:
  release:
    types: [published]

jobs:
  build_and_push:
    name: Build & Push Multi-Arch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: docker/setup-qemu-action@v2
      - id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - run: |
          docker buildx inspect multiarch || docker buildx create --name multiarch --use
          docker buildx inspect --bootstrap
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-cache-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('base/Dockerfile') }}
          restore-keys: |
            buildx-cache-${{ runner.os }}-${{ github.ref }}-
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tag-sha: true
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - uses: docker/build-push-action@v3
        with:
          builder: multiarch
          context: base
          file: base/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
            type=local,dest=/tmp/.buildx-cache,mode=max

